//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace OrleansDemo.GrainInterfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class Grain1Factory
    {
        

                        public static OrleansDemo.GrainInterfaces.IGrain1 GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansDemo.GrainInterfaces.IGrain1), -103877802, primaryKey));
                        }

                        public static OrleansDemo.GrainInterfaces.IGrain1 GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansDemo.GrainInterfaces.IGrain1), -103877802, primaryKey, grainClassNamePrefix));
                        }

                        public static OrleansDemo.GrainInterfaces.IGrain1 GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansDemo.GrainInterfaces.IGrain1), -103877802, primaryKey));
                        }

                        public static OrleansDemo.GrainInterfaces.IGrain1 GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansDemo.GrainInterfaces.IGrain1), -103877802, primaryKey, grainClassNamePrefix));
                        }

            public static OrleansDemo.GrainInterfaces.IGrain1 Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return Grain1Reference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("OrleansDemo.GrainInterfaces.OrleansDemo.GrainInterfaces.IGrain1")]
        internal class Grain1Reference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, OrleansDemo.GrainInterfaces.IGrain1
        {
            

            public static OrleansDemo.GrainInterfaces.IGrain1 Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (OrleansDemo.GrainInterfaces.IGrain1) global::Orleans.Runtime.GrainReference.CastInternal(typeof(OrleansDemo.GrainInterfaces.IGrain1), (global::Orleans.Runtime.GrainReference gr) => { return new Grain1Reference(gr);}, grainRef, -103877802);
            }
            
            protected internal Grain1Reference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal Grain1Reference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -103877802;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "OrleansDemo.GrainInterfaces.OrleansDemo.GrainInterfaces.IGrain1";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                Grain1Reference input = ((Grain1Reference)(original));
                return ((Grain1Reference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                Grain1Reference input = ((Grain1Reference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return Grain1Reference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return Grain1MethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<int> OrleansDemo.GrainInterfaces.IGrain1.GetSquaredValue(int @input)
            {

                return base.InvokeMethodAsync<System.Int32>(1690699485, new object[] {@input} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("OrleansDemo.GrainInterfaces.OrleansDemo.GrainInterfaces.IGrain1", -103877802)]
    internal class Grain1MethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -103877802;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -103877802:  // IGrain1
                        switch (methodId)
                        {
                            case 1690699485: 
                                return ((IGrain1)grain).GetSquaredValue((Int32)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -103877802:  // IGrain1
                    switch (methodId)
                    {
                        case 1690699485:
                            return "GetSquaredValue";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class PostalOrderFactory
    {
        

                        public static OrleansDemo.GrainInterfaces.IPostalOrder GetGrain(System.String primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansDemo.GrainInterfaces.IPostalOrder), 114829820, primaryKey));
                        }

                        public static OrleansDemo.GrainInterfaces.IPostalOrder GetGrain(System.String primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansDemo.GrainInterfaces.IPostalOrder), 114829820, primaryKey, grainClassNamePrefix));
                        }

            public static OrleansDemo.GrainInterfaces.IPostalOrder Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return PostalOrderReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("OrleansDemo.GrainInterfaces.OrleansDemo.GrainInterfaces.IPostalOrder")]
        internal class PostalOrderReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, OrleansDemo.GrainInterfaces.IPostalOrder
        {
            

            public static OrleansDemo.GrainInterfaces.IPostalOrder Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (OrleansDemo.GrainInterfaces.IPostalOrder) global::Orleans.Runtime.GrainReference.CastInternal(typeof(OrleansDemo.GrainInterfaces.IPostalOrder), (global::Orleans.Runtime.GrainReference gr) => { return new PostalOrderReference(gr);}, grainRef, 114829820);
            }
            
            protected internal PostalOrderReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal PostalOrderReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 114829820;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "OrleansDemo.GrainInterfaces.OrleansDemo.GrainInterfaces.IPostalOrder";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                PostalOrderReference input = ((PostalOrderReference)(original));
                return ((PostalOrderReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                PostalOrderReference input = ((PostalOrderReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return PostalOrderReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == -1277021679));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return PostalOrderMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task OrleansDemo.GrainInterfaces.IPostalOrder.UpdateShippingStatus(string @status, OrleansDemo.GrainInterfaces.ITruck @truck)
            {

                return base.InvokeMethodAsync<object>(-926269417, new object[] {@status, @truck is global::Orleans.Grain ? OrleansDemo.GrainInterfaces.TruckFactory.Cast(@truck.AsReference()) : @truck} );
            }
            
            System.Threading.Tasks.Task<string> OrleansDemo.GrainInterfaces.IPostalOrder.GetCurrentStatus()
            {

                return base.InvokeMethodAsync<System.String>(825167218, new object[] {} );
            }
            
            System.Threading.Tasks.Task<string> OrleansDemo.GrainInterfaces.IPostalOrder.GetTruckLocation()
            {

                return base.InvokeMethodAsync<System.String>(-389530197, new object[] {} );
            }
            
            System.Threading.Tasks.Task OrleansDemo.GrainInterfaces.IPostalOrder.CreateOrder(int @cost, string @name)
            {

                return base.InvokeMethodAsync<object>(1142032970, new object[] {@cost, @name} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("OrleansDemo.GrainInterfaces.OrleansDemo.GrainInterfaces.IPostalOrder", 114829820)]
    internal class PostalOrderMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 114829820;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 114829820:  // IPostalOrder
                        switch (methodId)
                        {
                            case -926269417: 
                                return ((IPostalOrder)grain).UpdateShippingStatus((String)arguments[0], (ITruck)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 825167218: 
                                return ((IPostalOrder)grain).GetCurrentStatus().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -389530197: 
                                return ((IPostalOrder)grain).GetTruckLocation().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 1142032970: 
                                return ((IPostalOrder)grain).CreateOrder((Int32)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case -1277021679:  // IGrainWithStringKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 114829820:  // IPostalOrder
                    switch (methodId)
                    {
                        case -926269417:
                            return "UpdateShippingStatus";
                    case 825167218:
                            return "GetCurrentStatus";
                    case -389530197:
                            return "GetTruckLocation";
                    case 1142032970:
                            return "CreateOrder";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case -1277021679:  // IGrainWithStringKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class TruckFactory
    {
        

                        public static OrleansDemo.GrainInterfaces.ITruck GetGrain(System.String primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansDemo.GrainInterfaces.ITruck), 689856320, primaryKey));
                        }

                        public static OrleansDemo.GrainInterfaces.ITruck GetGrain(System.String primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(OrleansDemo.GrainInterfaces.ITruck), 689856320, primaryKey, grainClassNamePrefix));
                        }

            public static OrleansDemo.GrainInterfaces.ITruck Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return TruckReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("OrleansDemo.GrainInterfaces.OrleansDemo.GrainInterfaces.ITruck")]
        internal class TruckReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, OrleansDemo.GrainInterfaces.ITruck
        {
            

            public static OrleansDemo.GrainInterfaces.ITruck Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (OrleansDemo.GrainInterfaces.ITruck) global::Orleans.Runtime.GrainReference.CastInternal(typeof(OrleansDemo.GrainInterfaces.ITruck), (global::Orleans.Runtime.GrainReference gr) => { return new TruckReference(gr);}, grainRef, 689856320);
            }
            
            protected internal TruckReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal TruckReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 689856320;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "OrleansDemo.GrainInterfaces.OrleansDemo.GrainInterfaces.ITruck";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                TruckReference input = ((TruckReference)(original));
                return ((TruckReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                TruckReference input = ((TruckReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return TruckReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == -1277021679));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return TruckMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task OrleansDemo.GrainInterfaces.ITruck.UpdateCurrentLocation(string @location)
            {

                return base.InvokeMethodAsync<object>(-2066867828, new object[] {@location} );
            }
            
            System.Threading.Tasks.Task<string> OrleansDemo.GrainInterfaces.ITruck.GetCurrentLocation()
            {

                return base.InvokeMethodAsync<System.String>(1302107453, new object[] {} );
            }
            
            System.Threading.Tasks.Task OrleansDemo.GrainInterfaces.ITruck.CreatePayload(IEnumerable<String> @orderNumbers)
            {

                return base.InvokeMethodAsync<object>(-880727137, new object[] {@orderNumbers} );
            }
            
            System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<OrleansDemo.GrainInterfaces.IPostalOrder>> OrleansDemo.GrainInterfaces.ITruck.GetPostalOrders()
            {

                return base.InvokeMethodAsync<System.Collections.Generic.IEnumerable<OrleansDemo.GrainInterfaces.IPostalOrder>>(-1576550956, new object[] {} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("OrleansDemo.GrainInterfaces.OrleansDemo.GrainInterfaces.ITruck", 689856320)]
    internal class TruckMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 689856320;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 689856320:  // ITruck
                        switch (methodId)
                        {
                            case -2066867828: 
                                return ((ITruck)grain).UpdateCurrentLocation((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1302107453: 
                                return ((ITruck)grain).GetCurrentLocation().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -880727137: 
                                return ((ITruck)grain).CreatePayload((IEnumerable<String>)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1576550956: 
                                return ((ITruck)grain).GetPostalOrders().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case -1277021679:  // IGrainWithStringKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 689856320:  // ITruck
                    switch (methodId)
                    {
                        case -2066867828:
                            return "UpdateCurrentLocation";
                    case 1302107453:
                            return "GetCurrentLocation";
                    case -880727137:
                            return "CreatePayload";
                    case -1576550956:
                            return "GetPostalOrders";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case -1277021679:  // IGrainWithStringKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
